---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    project: "${project.artifactId}"
    provider: "fabric8"
    version: "2.2.108"
    group: "io.fabric8.ipaas.apps"
    package: "zipkin"
  name: "kafka"
spec:
  replicas: 1
  selector:
    matchLabels:
      project: "${project.artifactId}"
      provider: "fabric8"
      group: "io.fabric8.ipaas.apps"
  template:
    metadata:
      labels:
        project: "${project.artifactId}"
        provider: "fabric8"
        version: "2.2.108"
        group: "io.fabric8.ipaas.apps"
        package: "zipkin"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/kafka:2.2.108"
        name: "kafka"
        ports:
        - containerPort: 9092
          name: "kafka"
        - containerPort: 8778
          name: "jolokia"
        volumeMounts:
        - mountPath: "/opt/kafka/logs"
          name: "logs"
          readOnly: false
      volumes:
      - emptyDir:
          medium: "Memory"
        name: "logs"
