---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    project: "${project.artifactId}"
    provider: "fabric8"
    version: "2.2.108"
    serverId: "2"
    group: "io.fabric8.ipaas.apps"
    package: "zipkin"
  name: "zookeeper-2"
spec:
  replicas: 1
  selector:
    matchLabels:
      project: "${project.artifactId}"
      provider: "fabric8"
      serverId: "2"
      group: "io.fabric8.ipaas.apps"
  template:
    metadata:
      labels:
        project: "${project.artifactId}"
        provider: "fabric8"
        version: "2.2.108"
        serverId: "2"
        group: "io.fabric8.ipaas.apps"
        package: "zipkin"
    spec:
      containers:
      - env:
        - name: "ENSEMBLE_SIZE"
          value: "3"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "SERVER_ID"
          value: "2"
        image: "fabric8/zookeeper:2.2.108"
        name: "zookeeper"
        ports:
        - containerPort: 2181
          name: "zkclient"
        - containerPort: 3888
          name: "election"
        - containerPort: 2888
          name: "peer"
        - containerPort: 8778
          name: "jolokia"
        volumeMounts:
        - mountPath: "/opt/zookeeper/data"
          name: "data"
          readOnly: false
        - mountPath: "/opt/zookeeper/log"
          name: "log"
          readOnly: false
      volumes:
      - emptyDir:
          medium: "Memory"
        name: "data"
      - emptyDir:
          medium: "Memory"
        name: "log"
