---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.zipkin"
  name: "zipkin-collector-admin"
spec:
  ports:
  - port: 9900
    protocol: "TCP"
    targetPort: 9900
  selector:
    project: "zipkin-collector"
    provider: "fabric8"
    group: "io.fabric8.zipkin"
  type: "LoadBalancer"
