---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    project: "${project.artifactId}"
    provider: "fabric8"
    version: "2.2.108"
    group: "io.fabric8.ipaas.apps"
    package: "zipkin-starter"
  name: "kafka"
spec:
  ports:
  - port: 9092
    protocol: "TCP"
    targetPort: 9092
  selector:
    project: "kafka"
    provider: "fabric8"
    group: "io.fabric8.ipaas.apps"
  type: "LoadBalancer"
