---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.zipkin"
    package: "zipkin-starter"
  name: "zipkin-mysql"
spec:
  ports:
  - port: 3306
    protocol: "TCP"
    targetPort: 3306
  selector:
    project: "zipkin-mysql"
    provider: "fabric8"
    group: "io.fabric8.zipkin"
  type: "LoadBalancer"
