---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.zipkin"
    package: "zipkin-starter-mysql"
  name: "zipkin-collector"
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: "fabric8"
      project: "${project.artifactId}"
      group: "io.fabric8.zipkin"
  template:
    metadata:
      labels:
        provider: "fabric8"
        project: "${project.artifactId}"
        version: "${project.version}"
        group: "io.fabric8.zipkin"
        package: "zipkin-starter-mysql"
    spec:
      containers:
      - env:
        - name: "STORAGE_PORT_9042_TCP_ADDR"
          value: "zipkin-cassandra:9411"
        - name: "KAFKA_ZOOKEEPER"
          value: "zookeeper:2181"
        - name: "STORAGE_PORT_3306_TCP_ADDR"
          value: "zipkin-mysql:3306"
        - name: "STORAGE_TYPE"
          value: "mysql"
        - name: "TRANSPORT_TYPE"
          value: "kafka"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "openzipkin/zipkin-collector:1.39.3"
        name: "zipkin-collector"
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
