---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    project: "${project.artifactId}"
    provider: "fabric8"
    version: "2.2.108"
    group: "io.fabric8.ipaas.apps"
    package: "zipkin-starter-mysql"
  name: "zookeeper-1"
spec:
  clusterIP: "None"
  ports:
  - name: "election"
    port: 3888
    targetPort: 3888
  - name: "peer"
    port: 2888
    targetPort: 2888
  selector:
    project: "zookeeper"
    provider: "fabric8"
    serverId: "1"
    group: "io.fabric8.ipaas.apps"
