---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    project: "${project.artifactId}"
    provider: "fabric8"
    version: "${project.version}"
    group: "io.fabric8.zipkin.examples"
  name: "zipkin-hello-world"
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "zipkin-hello-world"
    provider: "fabric8"
    group: "io.fabric8.zipkin.examples"
  type: "LoadBalancer"
