---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    project: "${project.artifactId}"
    provider: "fabric8"
    version: "${project.version}"
    group: "io.fabric8.zipkin.examples"
  name: "zipkin-hello-world"
spec:
  replicas: 1
  selector:
    matchLabels:
      project: "${project.artifactId}"
      provider: "fabric8"
      group: "io.fabric8.zipkin.examples"
  template:
    metadata:
      labels:
        project: "${project.artifactId}"
        provider: "fabric8"
        version: "${project.version}"
        group: "io.fabric8.zipkin.examples"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/zipkin-hello-world:${project.version}"
        name: "zipkin-hello-world"
        serviceAccountName: "fabric8"
        ports:
        - containerPort: 8080
          name: "http"
