---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.zipkin"
  name: "zipkin-mysql-cnf"
data:
  custom.cnf: |
    [mysqld]
    sql-mode=""
