---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.zipkin"
  name: "zipkin-mysql"
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: "fabric8"
      project: "${project.artifactId}"
      group: "io.fabric8.zipkin"
  template:
    metadata:
      labels:
        provider: "fabric8"
        project: "${project.artifactId}"
        version: "${project.version}"
        group: "io.fabric8.zipkin"
    spec:
      containers:
      - env:
        - name: "MYSQL_USER"
          value: "zipkin"
        - name: "MYSQL_PASSWORD"
          value: "zipkin"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "zipkin"
        - name: "MYSQL_DATABASE"
          value: "zipkin"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "mysql"
        name: "zipkin-mysql"
        readinessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 3306
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-init-script
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}
      - name: mysql-init-script
        configMap:
          name: zipkin-mysql-initdb