---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.zipkin"
  name: "zipkin"
spec:
  ports:
  - port: 9411
    protocol: "TCP"
    targetPort: 9411
  selector:
    project: "zipkin"
    provider: "fabric8"
    group: "io.fabric8.zipkin"
  type: "LoadBalancer"
